# Generated by Django 4.0.4 on 2022-04-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(help_text='Internal ID for private reference', primary_key=True, serialize=False, verbose_name='Song ID')),
                ('title', models.CharField(max_length=255)),
                ('isrc', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('SPOTIFY', 'Spotify'), ('YT', 'Yt')], max_length=10)),
                ('artist', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=255)),
                ('thumbnail_src', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pm_song',
                'ordering': ['song_id'],
            },
        ),
    ]
